CREATE TABLE HUMAN (
    HID RAW(16) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    SEX CHAR,
    BIRTH DATE NOT NULL,
    DEATH DATE,
    PID RAW(16),
    SIBORD INT,
    PRIMARY KEY (HID)
);

CREATE TABLE PARENTS (
    PID RAW(16) NOT NULL,
    FHID RAW(16),
    MHID RAW(16),
    CHILDCOUNT INT,
    PRIMARY KEY (PID),
    UNIQUE (FHID, MHID),
    FOREIGN KEY (FHID) REFERENCES HUMAN(HID)
        ON DELETE CASCADE,
    FOREIGN KEY (MHID) REFERENCES HUMAN(HID)
        ON DELETE CASCADE
);
CREATE INDEX PARENTS_FHID_IDX ON PARENTS (FHID);
CREATE INDEX PARENTS_MHID_IDX ON PARENTS (MHID);

ALTER TABLE HUMAN ADD CONSTRAINT HUMAN_FK_PID
    FOREIGN KEY (PID) REFERENCES PARENTS(PID)
        ON DELETE SET NULL;
