/* 부모들의 이름 */
CREATE OR REPLACE VIEW PARENTS_WITH_NAMES AS (
    SELECT P.PID, P.FHID, FH.NAME AS FHNAME, P.MHID, MH.NAME AS MHNAME, P.CHILDCOUNT
    FROM (PARENTS P
        LEFT OUTER JOIN HUMAN FH ON (P.FHID = FH.HID)
        LEFT OUTER JOIN HUMAN MH ON (P.MHID = MH.HID))
);

/* 사람과 그 사람 부모의 이름 */
CREATE OR REPLACE VIEW HUMAN_WITH_PARENTS AS (
    SELECT H.*, PN.FHID, PN.FHNAME, PN.MHID, PN.MHNAME, PN.CHILDCOUNT
        FROM HUMAN H LEFT OUTER JOIN PARENTS_WITH_NAMES PN ON (H.PID = PN.PID)
);
